language: swift

script:
    cache: cocoapods
    podfile: CMoviez/Podfile
    before_install:
    - gem install cocoapods # Since Travis is not always on latest version
    - pod install --project-directory=CMoiez
  xcode_project: CMoviez.xcworkspace # path to your xcodeproj folder
  xcode_scheme: CMoviezTests
  xcode_destination: platform=iOS Simulator,OS=10.1,name=iPad Pro (9.7-inch)
